### ISSUE TITLE
main is red: LLMTR imports the pre-move utils path, and the boundary test flakes at the 5s default

### ISSUE THREAD

**Issue by tombeckenham** [openstory-so/openstory#1490]
Two independent CI problems landed together on `main` (currently `a35dfec0`). `bun typecheck` and `bun knip` both fail on a clean checkout.

## 1. LLMTR imports the pre-move utils path (breaks typecheck + knip)

#1445 moved the shared utils to `src/shared`, and #1266 (merged after it) was written against the old path. Each was green on its own branch; together they are not.

```
src/lib/ai/llmtr.ts:34       import { typedEntries } from '@/lib/utils/typed-object';
src/lib/ai/llmtr.test.ts:24  import { typedEntries } from '@/lib/utils/typed-object';
```

The file lives at `src/shared/utils/typed-object.ts`. Six `error TS` in total: the unresolved module in each file, plus four `TS7031` implicit-any bindings in the test that are downstream of it. `bun knip` fails on the same edge ("Unresolved imports (1)").

## 2. `client-server-boundary.test.ts` flakes on the 5s default timeout

`no server-only module is reachable from client components/hooks/routes/functions` walks the whole client import graph synchronously. It takes ~5–9s under parallel load and there is no `testTimeout` set in `vitest.config.ts` or the file, so it intermittently dies with `Test timed out in 5000ms`.

Observed: fails when run alongside other suites, passes 3/3 when run alone. It is a timeout, not an assertion — no real boundary violation is involved.

## Fix

1. Repoint both imports at `@/shared/utils/typed-object`.
2. Give the graph-walk test an explicit timeout instead of the 5s default.
